### ISSUE TITLE
Initial Gameplay Design

### ISSUE THREAD

**Issue by TinyPandas** [RSA-Bots/RDA-Game#1]
- Perspective (2D or 3D)
- Theme (Toontown-esque or Runescape / etc)

**Comment by lolzmac** [comment]
Closed, game doesn't need good gameplay.

**Comment by hero-ku** [comment]
Theme/World Ideas (Ones I'd like):

- Samurai Period
- Eastern Mythology
- Dark Fantasy, Low-Tech Dwarven Aesthetic
- Atlantis/Aquatic
